corrected 100_manage_my_process file

diff --git a/0x05-processes_and_signals/100-process_and_pid_file b/0x05-processes_and_signals/100-process_and_pid_file
--- a/0x05-processes_and_signals/100-process_and_pid_file
+++ b/0x05-processes_and_signals/100-process_and_pid_file
@@ -7,18 +7,33 @@
 #   Deletes the file /var/run/holbertonscript.pid and terminates upon
 #+  receiving a SIGQUIT or SIGTERM.
 
-terminator() {
-  rm /var/run/holbertonscript.pid
+echo $$ > /var/run/myscript.pid
+
+# function to clean up and exit
+function cleanup_exit {
+  rm /var/run/myscript.pid
   exit
 }
 
-echo "$$" > /var/run/holbertonscript.pid
+# function to handle SIGTERM signal
+function handle_sigterm {
+  echo "I hate the kill command"
+}
 
+# function to handle SIGINT signal
+function handle_sigint {
+  echo "Y U no love me?!"
+}
+
+# set up signal handlers
+trap 'cleanup_exit' SIGQUIT SIGTERM
+trap 'handle_sigterm' SIGTERM
+trap 'handle_sigint' SIGINT
+
+# display message indefinitely
+echo "To infinity and beyond"
 while true
 do
-  echo "To infinity and beyond"
-  sleep 2
-  trap 'echo "Y U no love me?!"' SIGINT
-  trap 'echo "I hate the kill command" && terminator' SIGTERM
-  trap 'terminator' SIGQUIT
+  sleep 1
 done
+
